export enum ChainId {
  ETHEREUM = "ETHEREUM",
  OPTIMISM = "OPTIMISM",
  BSC = "BSC",
  XDAI = "XDAI",
  POLYGON = "POLYGON",
  FANTOM = "FANTOM",
  ARBITRUM = "ARBITRUM",
  AVALANCHE = "AVALANCHE",
  AURORA = "AURORA",
}
