name: Build Test
on: push

jobs:
  build_test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.1.4
      - uses: actions/setup-node@v4.0.2
        with:
          node-version: 20
      - run: yarn
      - run: yarn lint
      - run: yarn build
      - run: yarn test
